[phases.setup]
nixPkgs = [
  "nodejs_18",
  "ffmpeg",
  "fontconfig",
  "dejavu_fonts",
  "liberation_ttf",
  "roboto",              # ← Add this
  "noto-fonts",          # ← Add this
  "google-fonts"         # ← Add this (if available)
]

[phases.build]
cmds = [
  "mkdir -p /app/.fontconfig",              # Create fontconfig directory
  "mkdir -p /app/.cache/fontconfig",        # Create fontconfig cache directory
  "fc-cache -fv",                           # Rebuild font cache
  "fc-list | head -10"                      # Debug: list available fonts
]

[phases.start]
cmd = "cd audio-trimmer-server && npm start"

[phases.start.env]
FONTCONFIG_PATH = "/etc/fonts:/app/.fontconfig"
FONTCONFIG_FILE = "/etc/fonts/fonts.conf"
XDG_CACHE_HOME = "/app/.cache"