# Railway nixpacks configuration for video generation
providers = ["node"]

[phases.setup]
aptPackages = ["ffmpeg"]

[phases.build]
cmds = [
  "cd audio-trimmer-server",
  "npm install",
  "npm rebuild sharp"
]

[variables]
SHARP_IGNORE_GLOBAL_LIBVIPS = "1"
NODE_ENV = "production"