[phases.setup]
nixPkgs = [
  "nodejs_18",
  "ffmpeg",
  "fontconfig",
  "dejavu_fonts",
  "liberation_ttf",
  "roboto",
  "roboto-slab",
  "opensans-ttf"
]

[phases.build]
cmds = [
  "mkdir -p /app/.fontconfig",
  "mkdir -p /app/.cache/fontconfig",
  "mkdir -p /usr/share/fonts/truetype/custom",
  "fc-cache -fv",
  "fc-list | grep -i roboto || echo 'No Roboto found'",
  "fc-list | grep -i arial || echo 'No Arial found'"
]

[phases.start]
cmd = "cd audio-trimmer-server && npm start"

[phases.start.env]
FONTCONFIG_PATH = "/etc/fonts:/app/.fontconfig"
FONTCONFIG_FILE = "/etc/fonts/fonts.conf"
XDG_CACHE_HOME = "/app/.cache"
FC_DEBUG = "1"