[phases.setup]
nixPkgs = ['nodejs_18', 'ffmpeg', 'fontconfig', 'roboto', 'dejavu_fonts']

[phases.build]
cmds = [
  'mkdir -p /app/fonts',
  'fc-cache -fv',
  'echo "Testing font access:" && fc-list | grep -i roboto || true'
]

[phases.start]
cmd = "cd audio-trimmer-server && npm start"

[phases.start.env]
FONTCONFIG_PATH = "/app/.fontconfig:/etc/fonts"
FONTCONFIG_FILE = "/app/.fontconfig/fonts.conf"
XDG_CACHE_HOME = "/app/.cache"