# Railway nixpacks configuration for video generation
[providers]
node = "18"

[phases.setup]
# Install system dependencies for video processing
aptPackages = ["ffmpeg"]

[phases.build]
cmds = [
  "cd audio-trimmer-server",
  "npm install",
  "npm rebuild sharp"
]

[variables]
# Ensure Sharp uses correct platform binaries
SHARP_IGNORE_GLOBAL_LIBVIPS = "1"
NODE_ENV = "production"