# Railway nixpacks configuration for video generation
[providers]
node = "18"

[phases.build]
cmds = [
  "npm install",
  # Rebuild Sharp for Railway's container architecture
  "npm rebuild sharp"
]

[phases.install]
# Install system dependencies for video processing
apt = ["ffmpeg"]

[variables]
# Ensure Sharp uses correct platform binaries
SHARP_IGNORE_GLOBAL_LIBVIPS = "1"
# Railway specific Sharp configuration
NODE_ENV = "production"